version: "4.0"

actions:
  icd10_apcs:
    run: >
      sqlrunner:latest
        --output output/icd10-apcs.csv
        --log-file output/icd10-apcs-log.json
        analysis/query-icd10-apcs.sql
    outputs:
      moderately_sensitive:
        counts: output/icd10-apcs.csv
        log: output/icd10-apcs-log.json
