version: "4.0"

actions:
  icd10_apcs:
    run: >
      sqlrunner:latest
        --output output/icd10_apcs.csv
        --log-file output/icd10_apcs_log.json
        analysis/query_icd10_apcs.sql
    outputs:
      moderately_sensitive:
        counts: output/icd10_apcs.csv
        log: output/icd10_apcs_log.json

  icd10_ons_deaths:
    run: >
      sqlrunner:latest
        --output output/icd10_ons_deaths.csv
        --log-file output/icd10_ons_deaths_log.json
        analysis/query_icd10_ons_deaths.sql
    outputs:
      moderately_sensitive:
        counts: output/icd10_ons_deaths.csv
        log: output/icd10_ons_deaths_log.json

  validate_output:
    run: python:latest python analysis/validate_output.py
    needs:
      - icd10_apcs
      - icd10_ons_deaths
    outputs:
      moderately_sensitive:
        report: output/validation_report.txt
